name: NSIS Installer Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Checkout Code.
      uses: actions/checkout@v4
    - name: Install NSIS
      run: |
        bash -c 'echo "deb http://ftp.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
        apt-get -y update
        apt-get -y install -t unstable nsis
    - name: Print NSIS version
      run: makensis ./installer/installer.nsi
      
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./installer/RPGModManagerInstall.exe
        generate_release_notes: true
        
      env:
        GITHUB_TOKEN: ${{ github.token }}
