name: Compile Documenation
permissions:
  contents: write

on:
  push:
    branches:
      - master
      - multipalyer
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./www/mods
          output_dir: ./www/dev/DevDocs
          config_file: ./www/dev/conf.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./www/dev/DevDocs
