name: NSIS Installer Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Checkout Code.
      uses: actions/checkout@v4
    - name: Create installer
      uses: joncloud/makensis-action@v4
      with:
        script-file: "./installer/installer.nsi"
        arguments: "/V3"
