name: NSIS Installer Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Checkout Code.
      uses: actions/checkout@v4
    - name: Install NSIS
      run: |
        bash -c 'echo "deb http://ftp.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
        apt-get -y update
        apt-get -y install -t unstable nsis
    - name: Print NSIS version
      run: makensis ./installer/installer.nsi

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: nsisInstallers
        path: ./installer/
