name: Compile Documenation
permissions:
    contents: read
    pages: write
    id-token: write

on:  
    push:
        branches:
          - master
          - main
          - multipalyer

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code.
        uses: actions/checkout@v4
        
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build:docs:prod
      - name: Download EnVar plugin for NSIS
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip
          file-name: envar_plugin.zip
          location: ${{ github.workspace }}

      - name: Extract EnVar plugin
        run: 7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/envar_plugin.zip"

      - name: 'Install makensis (apt)'
        run: sudo apt update && sudo apt install -y nsis nsis-pluginapi
        if: ${{ matrix.os == 'ubuntu-20.04' }}

      - name: 'Install makensis (homebrew)'
        run: brew update && brew install makensis
        if: ${{ matrix.os == 'macos-latest' }}

      - name: 'Set Plugin permissions'
        run: sudo chown -R $(whoami) /usr/share/nsis/Plugins/
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        
      - name: Create installer
        uses: joncloud/makensis-action@v4
        with:
          script-file: "./installer/installer.nsi"
          arguments: "/V3"
          
        
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: ./out
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './out'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        


